### ISSUE TITLE
Remapping MC Jars throws ArrayOutOfBoundsException

### ISSUE THREAD

**Issue by ghost** [PatchworkMC/patchwork-patcher#97]
<a href="https://pastebin.com/raw/Y8Sf74t9">The error Message</a>. I looked at the code and noticed at
net.patchworkmc.patcher.mapping.Tsrg.readMappings(Tsrg.java:43) (the exact error line)
there is a assumption of a length 2 or more. if this is needed, then I would recommend having a try catch to throw a more descriptive error.

**Comment by MisterSilvereagle** [comment]
Got the same error. 

If the developers need a output, here it is:

`[main/INFO] (PatchworkUI) Welcome to Patchwork Patcher!
[main/INFO] (PatchworkUI) Patchwork is still an early project, things might not work as expected! Let us know the issues on GitHub!
[pool-2-thread-1/WARN] (Patchwork) Merged minecraft jar not found, generating one!
[pool-2-thread-1/INFO] (ResourceDownloader) Downloading Minecraft jars
[pool-2-thread-1/INFO] (ResourceDownloader) Merging and remapping Minecraft jars
[pool-2-thread-1/ERROR] (Patchwork) Couldn't setup Patchwork!
 java.lang.ArrayIndexOutOfBoundsException: 1
	at net.patchworkmc.patcher.mapping.Tsrg.readMappings(Tsrg.java:43) ~[patchwork-patcher-0.5-SNAPSHOT-ui.jar:0.5-SNAPSHOT]
	at net.patchworkmc.patcher.util.ResourceDownloader.setupAndLoadMappings(ResourceDownloader.java:99) ~[patchwork-patcher-0.5-SNAPSHOT-ui.jar:0.5-SNAPSHOT]
	at net.patchworkmc.patcher.util.ResourceDownloader.createAndRemapMinecraftJar(ResourceDownloader.java:75) ~[patchwork-patcher-0.5-SNAPSHOT-ui.jar:0.5-SNAPSHOT]
	at net.patchworkmc.patcher.Patchwork.createInner(Patchwork.java:414) ~[patchwork-patcher-0.5-SNAPSHOT-ui.jar:0.5-SNAPSHOT]
	at net.patchworkmc.patcher.Patchwork.create(Patchwork.java:372) ~[patchwork-patcher-0.5-SNAPSHOT-ui.jar:0.5-SNAPSHOT]
	at net.patchworkmc.patcher.ui.PatchworkUI.startPatching(PatchworkUI.java:300) ~[patchwork-patcher-0.5-SNAPSHOT-ui.jar:0.5-SNAPSHOT]
	at net.patchworkmc.patcher.ui.PatchworkUI.lambda$null$9(PatchworkUI.java:265) ~[patchwork-patcher-0.5-SNAPSHOT-ui.jar:0.5-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_281]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_281]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_281]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_281]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
`

Hope you can help, this is an awesome project!

**Comment by chxlky** [comment]
Can confirm, has happened to me too. Although perhaps a temporary solution would be to use patcher v0.3. (1.16.4 mods are internally compatible with 1.16.5, so it should work, _i think_) This happened to me on v0.4, now that I've seen you're using a pre-release snapshot of v0.5.

**Comment by cittyinthecloud** [comment]
SRG changed their format and the mapping downloader for 1.16.5 is broke, not sure if we wanna hard code an older URL or what

**Comment by shedaniel** [comment]
You gonna make this download from the mcp config maven, because that wasn’t changed.
